### PR TITLE
Fix the positioning of the buttons

### LINKED ISSUE #5: Buttons positioning is broken

### PR DESCRIPTION
**Pull request by JonasTrampe**
fixes #5

### CODE REVIEW

File: webserver/static/js/custom_blocks_events.js [hunk 1]
```diff
@@ -134,10 +134,12 @@ Blockly.Python.event_button_object = function(block) {
...
-    var x = Blockly.Python.valueToCode(block, 'X', Blockly.Python.ORDER_ATOMIC) || '0';
-    var y = Blockly.Python.valueToCode(block, 'Y', Blockly.Python.ORDER_ATOMIC) || '0';
-    var width = Blockly.Python.valueToCode(block, 'Width', Blockly.Python.ORDER_ATOMIC) || '1';
-    var height = Blockly.Python.valueToCode(block, 'Height', Blockly.Python.ORDER_ATOMIC) || '1';
+
+    let values = this.getInput('Values')
+    let x = values.fieldRow.find(({name}) => name === 'X').getValue() || 0
+    let y = values.fieldRow.find(({name}) => name === 'Y').getValue() || 0
+    let width  = values.fieldRow.find(({name}) => name === 'Width').getValue() || 1
+    let height = values.fieldRow.find(({name}) => name === 'Height').getValue() || 1
```
Comment (toklinke) [inline webserver/static/js/custom_blocks_events.js:142]: We have nearly identical code above in callback for `setOnChange()`.
The only difference is that the latter is missing the default fallback values `|| 0` or `|| 1`. Shouldn't we always use fallback values?
Moreover, can we reduce duplicated code by extracting a function for getting these values?
